package com.dailyservice.whatsappbot.model.v1;

public enum LastSelectedMenu {
	
	MAIN,
	MENU_RESET,
	HASH,
	START,
	PLACE_ORDER,
	PLACE_ORDER_ONE_TIME,
	PLACE_ORDER_ONE_TIME_STEP_1,
	PLACE_ORDER_ONE_TIME_STEP_2,
	PLACE_ORDER_ITEM_CONFIRMED,
	PLACE_ORDER_QWT_CONFIRMED,
	PLACE_ORDER_ADDRESS_CONFIRMED,
	SELECT_QWT_CONFIRM,
	PAYMENT_METHOD_CONFIRMED,
	USER_CONFIRMED_ORDER,
	CONFIRM_QUANTITY,
	PAYMENT_UPI_INIT,
	PLACE_ORDER_MONTHLY,
	PLACE_ORDER_MONTHLY_STEP_1,
	LAST_ORDER_FAILED,
	ORDER_STATUS,
	LAST_ORDER_SUCCESS,
	MY_SUBSCRIPTION,
	MONTHLY_SUBSCRIBED, ORDER_DETAILS, SUBSCRIPTION_DETAILS
	

}
